wallpaper {
    # Vuoto = wallpaper di fallback per i monitor.
    monitor =

    # Passiamo direttamente la directory.
    path = ~/dotfiles/wallpapers

    # Riempie lo schermo mantenendo le proporzioni.
    fit_mode = cover

    # Cambia wallpaper ogni 10 minuti.
    # Il valore è espresso in secondi.
    timeout = 600

    # Qui imposteremo l'ordine delle immagini.
    # Possiamo scegliere quello più adatto una volta verificati
    # i valori supportati dalla nostra versione.
}