# Configurazione del display manager SDDM.
#
# Questo file non configura l'aspetto dettagliato di SilentSDDM.
# Dice invece a SDDM quale tema usare e quali variabili servono
# al greeter.

[General]

# SilentSDDM utilizza la tastiera virtuale Qt.
InputMethod=qtvirtualkeyboard

# Rende disponibili al greeter i componenti QML di SilentSDDM
# e configura Qt Virtual Keyboard.
GreeterEnvironment=QML2_IMPORT_PATH=/usr/share/sddm/themes/silent/components/,QT_IM_MODULE=qtvirtualkeyboard


[Theme]

# Tema utilizzato dal greeter SDDM.
Current=silent